---
- name: Install Disable THP Service
  become: yes
  template:
      src: "templates/{{ ansible_distribution }}-disable-transparent-huge-pages.service.j2"
      dest: "/etc/systemd/system/disable-transparent-huge-pages.service"
      mode: 0555
  when: thp_disable

- name: Enable Service
  become: yes
  systemd:
      name: disable-transparent-huge-pages.service
      enabled: yes
      daemon_reload: yes
      state: restarted
  when: thp_disable

- name: Test Changes
  command: "cat /sys/kernel/mm/transparent_hugepage/enabled"
  when: thp_disable

- name: Test Changes
  command: "cat /sys/kernel/mm/transparent_hugepage/defrag"
  when: thp_disable
